# See:
# - https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
# - https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

[project]
name = "cson-pipeline"
version = "2025.04.08"
authors = "SCAPE"
description = "From CSON pipeline for processing data into ML-ready formats"
readme = "README.md"
requires-python = ">=3.10,<=3.13.2"

# Please specify dependencies in alphabetical order
dependencies = [
    "fastkml>=1.1.0", # FastKML is a library for parsing and writing KML (Keyhole Markup Language) files.
    "folium>=0.19.5", # Folium is a library for creating interactive maps using Leaflet.js.
    "geopandas>=1.0.1", # GeoPandas is a library that allows geospatial plotting with latitudes and longitudes
    "lz4>=4.4.4", # LZ4 is a fast compression algorithm.
    "matplotlib>=3.10.0", # Matplotlib is a comprehensive library for visualizations in Python.
    "numpy>=2.2.1", # NumPy is a library for numerical computing in Python.
    "obspy>=1.4.1", # ObsPy is a Python toolbox for seismology.
    "pandas>=2.2.3", # pandas is a library for data manipulation and analysis in Python.
    "pyod>=2.0.4", # PyOD is a library that contains wrappers for outlier detection models
    "quantum-inferno>=1.1.3",
    "redvox>=3.8.7",
    "scikit-image>=0.25.1", # Scikit-image is a library for image processing in Python.
    "scikit-learn>=1.6.1", # Scikit-learn is a library for machine learning in Python.
    "scipy>=1.15.0", # SciPy is a library for scientific computing in Python.
]

[project.urls]
homepage = "https://github.com/ISLA-UH/cson_pipeline.git"

[tool.setuptools.packages.find]
exclude = ["qi*"]